Bookshelf.Web/ViewModels/Book/BookDetailsViewModel.cs
namespace Bookshelf.Web.ViewModels.Book;

public class BookDetailsViewModel
{
    public int Id { get; init; }
    public string Title { get; init; }
    public string? Subtitle { get; init; }
    public string ISBN { get; init; }
    public int Pages { get; init; }
    public string PublishingCompany { get; init; }
    public string Synopsis { get; init; }
    public List<string> Authors { get; init; } = new();
    public List<string> Genres { get; init; } = new();
    public int Rate { get; set; }
    public List<Review> Reviews { get; set; } = new();
}

public class Review
{
    public string Reader { get; set; }
    public string Content { get; set; }
}

Bookshelf.Web/ViewModels/Book/BookSearchViewModel.cs
namespace Bookshelf.Web.ViewModels.Book
{
    public class BookSearchViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string? Subtitle { get; set; }
        public List<string> Authors { get; set; }
        public List<string> Genres { get; set; }
    }
}

Bookshelf.Web/Controllers/BookController.cs
using Bookshelf.Web.Services;
using Microsoft.AspNetCore.Mvc;

namespace Bookshelf.Web.Controllers
{
    public class BookController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] string query,
            [FromServices] BookService bookService)
        {
            ViewData["query"] = query;
            var books = await bookService.SearchBooksAsync(query);

            return View(books);
        }

        [HttpGet("/Details/{id:int}")]
        public async Task<IActionResult> Details([FromRoute] int id,
            [FromServices] BookService bookService)
        {
            var book = await bookService.GetBookDetailsAsync(id);

            if (book == null)
                return NotFound();

            return View(book);
        }
    }
}

Bookshelf.Web/Controllers/ReadingController.cs
using Bookshelf.Web.Extensions;
using Bookshelf.Web.Services;
using Bookshelf.Web.ViewModels.Reading;
using Microsoft.AspNetCore.Mvc;

namespace Bookshelf.Web.Controllers
{
    public class ReadingController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> Index([FromServices] ReadingService readingService)
        {
            if (HttpContext.GetValueFromSession("token") == null)
                return RedirectToAction("Index", "Account");

            var readings = await readingService.GetReadingsAsync(HttpContext.GetValueFromSession("token"));

            return View(readings);
        }

        [HttpGet("/AddReading")]
        public async Task<IActionResult> AddReading([FromServices] ReadingService readingService,
            [FromQuery] int bookId)
        {
            if (HttpContext.GetValueFromSession("token") == null)
                return RedirectToAction("Index", "Account");

            var viewModel = new AddReadingViewModel
            {
                BookId = bookId
            };

            var result = await readingService.AddReadingAsync(HttpContext.GetValueFromSession("token"),
                viewModel);

            if (result == true)
                return RedirectToAction(nameof(Index));
            else
                return BadRequest("Não foi possível adicionar uma nova leitura");
        }

        [HttpGet("/Update/{id:int}")]
        public async Task<IActionResult> Update([FromServices] ReadingService readingService,
            [FromRoute] int id)
        {
            var reading = await readingService.GetReadingAsync(HttpContext.GetValueFromSession("token"),
                id);

            return View(reading);
        }

        [HttpPost("/Update/{id:int}")]
        public async Task<IActionResult> Update([FromServices] ReadingService readingService,
            [FromForm] DetailsReadingViewModel viewModel)
        {
            var updateViewModel = new UpdateReadingViewModel
            {
                Id = viewModel.Id,
                PagesRead = viewModel.PagesRead,
                ReadingStatus = viewModel.ReadingStatus,
                Rate = viewModel.Rate,
                Review = viewModel.Review
            };

            var result = await readingService.UpdateReadingAsync(HttpContext.GetValueFromSession("token"),
                updateViewModel);

            if (result == true)
                return RedirectToAction(nameof(Index));

            return BadRequest("Não foi possível atualizar a leitura!");
        }

        [HttpGet("/Delete/{id:int}")]
        public async Task<IActionResult> Delete([FromServices] ReadingService readingService,
            [FromRoute] int id)
        {
            var reading = await readingService.GetReadingAsync(HttpContext.GetValueFromSession("token"),
                id);

            return View(reading);
        }

        [HttpPost("/Delete/{id:int}")]
        public async Task<IActionResult> Delete([FromServices] ReadingService readingService,
            [FromForm] DetailsReadingViewModel viewModel)
        {
            var result = await readingService.DeleteReadingAsync(HttpContext.GetValueFromSession("token"),
                viewModel.Id);

            if (result == true)
                return RedirectToAction(nameof(Index));

            return BadRequest("Não foi possível deletar a leitura!");
        }
    }
}

Bookshelf.Web/Views/Book/Details.cshtml
@model Bookshelf.Web.ViewModels.Book.BookDetailsViewModel;

<div class="container mt-5">
    <div class="row">
        <div class="col-md-12 d-flex justify-content-center align-items-center">
            <div>
                <h1>Detalhes do livro</h1>
                <dl>
                    <dt class="col-md-3">
                        <strong>Título:</strong>
                    </dt>
                    <dd class="col-md-9">
                        @Model.Title
                    </dd>
                    <dt class="col-md-3">
                        <strong>Subtítulo:</strong>
                    </dt>
                    <dd class="col-md-9">
                        @Model.Subtitle
                    </dd>
                    <dt class="col-md-3">
                        <strong>ISBN:</strong>
                    </dt>
                    <dd class="col-md-9">
                        @Model.ISBN
                    </dd>
                    <dt class="col-md-3">
                        <strong>Páginas:</strong>
                    </dt>
                    <dd class="col-md-9">
                        @Model.Pages
                    </dd>
                    <dt class="col-md-3">
                        <strong>Editora:</strong>
                    </dt>
                    <dd class="col-md-9">
                        @Model.PublishingCompany
                    </dd>
                    <dt class="col-md-3">
                        <strong>Sinopse:</strong>
                    </dt>
                    <dd class="col-md-9">
                        <p style="text-align: justify">@Model.Synopsis</p>
                    </dd>
                    <dt class="col-md-3">
                        <strong>Autor(es):</strong>
                    </dt>
                    <dd class="col-md-9">
                        @if (Model.Authors.Count > 1)
                        {
                            @for (int x = 0; x < Model.Authors.Count - 1; x++)
                            {
                                @Html.DisplayFor(model => Model.Authors[x])

                                <span>,</span>
                            }
                            @Html.DisplayFor(model => Model.Authors[Model.Authors.Count - 1])
                        }
                        else
                        {
                            @Html.DisplayFor(model => Model.Authors[0])
                        }
                    </dd>
                    <dt class="col-md-3">
                        <strong>Gênero(s):</strong>
                    </dt>
                    <dd class="col-md-9">
                        @if (Model.Genres.Count > 1)
                        {
                            @for (int x = 0; x < Model.Genres.Count - 1; x++)
                            {
                                @Html.DisplayFor(model => Model.Genres[x])

                                <span>,</span>
                            }
                            @Html.DisplayFor(model => Model.Genres[Model.Genres.Count - 1])
                        }
                        else
                        {
                            @Html.DisplayFor(model => Model.Genres[0])
                        }
                    </dd>
                    <dt class="col-md-3">
                        <strong>Avaliação:</strong>
                    </dt>
                    <dd class="col-md-9">
                        <p style="text-align: justify">@Model.Rate / 5</p>
                    </dd>
                </dl>
                <a class="btn btn-primary" asp-controller="Reading" asp-action="AddReading"
                   asp-route-bookId="@Model.Id">Adicionar a lista</a>

                <br />

                <h2>Reviews dos leitores</h2>
                @if (Model.Reviews.Count > 0)
                {
                    foreach (var item in Model.Reviews)
                    {
                        if (item.Content is not null)
                        {
                            <div>
                                <p>
                                    <strong>@Html.DisplayFor(modelItem => item.Reader)</strong> <br />
                                    @Html.DisplayFor(modelItem => item.Content)
                                </p>
                            </div>
                        }
                    }
                }
            </div>
        </div>
    </div>
</div>

Bookshelf.Web/Views/Book/Index.cshtml
@model IEnumerable<Bookshelf.Web.ViewModels.Book.BookSearchViewModel>

<div class="container-md">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <form asp-controller="Book" method="get">
                <div class="input-group">
                    <input type="search" class="form-control" id="query" name="query" placeholder="Pesquisar livros pelo título, ISBN ou autor" aria-label="Pesquisa" value="@ViewData["query"]" />
                    <button type="submit" class="btn btn-outline-success">Pesquisar</button>
                </div>
            </form>
        </div>
    </div>
</div>
@if (Model.Count() == 0)
{
    <h1 class="text-warning">Ops parace que este livro não existe no nosso banco de dados!</h1>
}
else
{
    <h1 class="text-center">Resultado da pesquisa</h1>
    <hr />
    <div class="container-md">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <ul class="list-group">
                    @foreach (var item in Model)
                    {
                        <li class="list-group-item">
                            <div class="media-body">
                                <h4>@Html.DisplayFor(model => item.Title)</h4>
                                <p>
                                    <b>Autor(es):</b> @foreach (var author in item.Authors)
                                    {
                                        @Html.DisplayFor(model => author)
                                    }
                                </p>
                                <p>
                                    <b>Gêneros:</b> @for (int x = 0; x < item.Genres.Count - 1; x++)
                                    {
                                        @Html.DisplayFor(model => item.Genres[x])
                                        ;
                                        <span>,</span>
                                    }
                                    @Html.DisplayFor(model => item.Genres[item.Genres.Count - 1])
                                </p>
                            </div>
                        </li>
                        <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.Id">Detalhes</a>
                        <a class="btn btn-secondary" asp-controller="Reading" asp-action="AddReading"
                           asp-route-bookId="@item.Id">Adicionar a lista</a>
                    }
                </ul>
            </div>
        </div>
    </div>
}